### ISSUE TITLE
Error while running the eel project exe file with no console

### ISSUE THREAD

**Issue by Satya9348** [python-eel/Eel#700]
I have converted my eel project to an executable file with console and It is running smoothly. But whenever I tries it with no console it makes an exe file but gives me error whenever I opens it. The error is below.
Traceback (most recent call last):
  File "main.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "eel\__init__.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "bottle.py", line 73, in <module>
AttributeError: 'NoneType' object has no attribute 'write'

**Plese help me with it...**

**Comment by artydev** [comment]
same issue +1

**Comment by plusseed** [comment]
Eel is importing a bottle,
but AttributeError cannot be caught in bottle.py

https://docs.python.org/3.11/library/sys.html?highlight=sys#module-sys

It is written as below.

```
Note Under some conditions stdin, stdout and stderr as well as the original values __stdin__, __stdout__ and __stderr__ can be None. It is usually the case for Windows GUI apps that aren’t connected to a console and Python apps started with pythonw.
```

There is also a way to edit bottle.py directly,
but I assign null to stdout and stderr and throw it away.

```
import os
import sys
sys.stdout = open(os.devnull, 'w')
sys.stderr = open(os.devnull, 'w')
import eel
```

# Sorry, Generated by translation

**Comment by gorkemgul** [comment]
> Eel is importing a bottle, but AttributeError cannot be caught in bottle.py
> 
> https://docs.python.org/3.11/library/sys.html?highlight=sys#module-sys
> 
> It is written as below.
> 
> ```
> Note Under some conditions stdin, stdout and stderr as well as the original values __stdin__, __stdout__ and __stderr__ can be None. It is usually the case for Windows GUI apps that aren’t connected to a console and Python apps started with pythonw.
> ```
> 
> There is also a way to edit bottle.py directly, but I assign null to stdout and stderr and throw it away.
> 
> ```
> import os
> import sys
> sys.stdout = open(os.devnull, 'w')
> sys.stderr = open(os.devnull, 'w')
> import eel
> ```
> 
> Sorry, Generated by translation

definitely works, much obliged.
