### ISSUE TITLE
Does not correctly report errors from Javascript

### ISSUE THREAD

**Issue by Kcuong93** [python-eel/Eel#707]
eel v0.16.0
Python 3.11.2
windows 10

I run a test on [examples/01 - hello_world](https://github.com/ChrisKnott/Eel/tree/master/examples/01%20-%20hello_world)
but make an error in hello.html (y is not defined)
```
<!DOCTYPE html>
<html>
  <head>
    <title>Hello, World!</title>

    <!-- Include eel.js - note this file doesn't exist in the 'web' directory -->
    <script type="text/javascript" src="/eel.js"></script>
    <script type="text/javascript">
      eel.expose(say_hello_js); // Expose this function to Python
      function say_hello_js(x) {

        // ------------------------
        console.log("Hello from " + y); //y is not defined
        // ------------------------
        
      }

      say_hello_js("Javascript World!");
      eel.say_hello_py("Javascript World!"); // Call a Python function
    </script>
  </head>

  <body>
    Hello, World!
  </body>
</html>
```
hello.py:
``` 
import eel

eel.init(r'C:\Users\9\Desktop\toolCoding\Python\testEel\gui')
@eel.expose                         # Expose this function to Javascript
def say_hello_py(x):
    print('Hello from %s' % x)

say_hello_py('Python World!')
eel.say_hello_js('Python World!')   # Call a Javascript function


eel.start('hello.html', port=0)
```

VScode reports an error:
```
Hello from Python World!
Traceback (most recent call last):
  File "src\\gevent\\greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "C:\Users\9\AppData\Roaming\Python\Python311\site-packages\eel\__init__.py", line 309, in _process_message
    _call_return_values[call_id] = message['value']
                                   ~~~~~~~^^^^^^^^^
KeyError: 'value'
2023-10-17T07:21:19Z <Greenlet at 0x26283c3c9a0: _process_message({'return': 1.0383343022168376, 'status': 'error', , <geventwebsocket.websocket.WebSocket object at 0x0)> failed with KeyError 
```

After checking the __init__.py, I found the message quite clear, so I added:

``` 
elif 'return' in message:
        call_id = message['return']
        if call_id in _call_return_callbacks:
            callback, error_callback = _call_return_callbacks.pop(call_id)
            if message['status'] == 'ok':
                callback(message['value'])
            elif message['status'] == 'error' and error_callback is not None:
                error_callback(message['error'], message['stack'])
        else:
            if message['status'] == 'error':
                print(message['error'])
                print(message['stack'])
            else:
                _call_return_values[call_id] = message['value']
 ```

then run again and VScode reports:

```
Hello from Python World!
y is not defined
ReferenceError: y is not defined
    at Object.say_hello_js (http://localhost:55327/hello.html:13:37)
    at eel._websocket.onmessage (http://localhost:55327/eel.js:135:82)
```

So is this a bug or is there a problem with the program or my computer?

**Comment by MauBorre** [comment]
Very nice! And it could be even better. Will try to come up with something and post it here.
Still I don't think this is a bug but an enhancement proposal? Perhaps a maintaintor could enlighten us a bit

**Comment by Kcuong93** [comment]
> Very nice! And it could be even better. Will try to come up with something and post it here. Still I don't think this is a bug but an enhancement proposal? Perhaps a maintaintor could enlighten us a bit

yes! Sorry about the bug label. Im newbie.
